CREATE DATABASE RESTURANTDB
USE RESTURANTDB

CREATE TABLE FOODCAT(
CATID INT PRIMARY KEY IDENTITY,
CATNAME VARCHAR(255) NOT NULL UNIQUE
)
SELECT * FROM FOODCAT
INSERT INTO FOODCAT VALUES('CHINES'),('FAST FOOD'),('CONTINENTIAL')


CREATE TABLE FOODS(
FID INT PRIMARY KEY IDENTITY,
FNAME VARCHAR(MAX),
PRICE FLOAT,
CATID INT,
FOREIGN KEY (CATID) REFERENCES FOODCAT(CATID)
)
INSERT INTO FOODS VALUES('ITEM 1',250,1)
INSERT INTO FOODS VALUES('ITEM 2',230,1)
INSERT INTO FOODS VALUES('ITEM 3',500,2)
SELECT * FROM FOODS

SELECT F.FID,F.FNAME,C.CATNAME,F.PRICE FROM FOODS f
INNER JOIN FOODCAT c
ON F.CATID = C.CATID


CREATE TABLE ORDERS(
ORDERID INT PRIMARY KEY IDENTITY,
FID INT,
QUANTITY INT,
CUSID INT,
TABNUM VARCHAR(255),

ORDATE DATE

)

SELECT * FROM ORDERS

INSERT INTO ORDERS VALUES(1,3,2,'TNB1',GETDATE())

TRUNCATE TABLE ORDERS


SELECT * FROM ORDERS

SELECT o.ORDERID,o.CUSID,f.FNAME,f.PRICE,o.QUANTITY, (F.PRICE * O.QUANTITY) 'TOTAL PRICE' FROM ORDERS o
INNER JOIN FOODS f
ON O.FID = f.FID
WHERE O.CUSID = 1


SELECT SUM((F.PRICE * O.QUANTITY)) 'TOTAL PRICE' FROM ORDERS o
INNER JOIN FOODS f
ON O.FID = f.FID
WHERE O.CUSID = 1